### PR TITLE
For hatch

### PR DESCRIPTION
**Pull request by thanhsol**
[Hatch] Add gradient colors
[Hatch] Fix bug when get definitions of gradient hatch

### CODE REVIEW

**Comment by chuongmep** [comment]
Hi @thanhsol, many thanks for your contribute, I don't see any new in this, please don't change format code, if you need refactor code, please create another pull request, just pull request feature you need, thanks you.

**Comment by thanhsol** [comment]
Hi, I just added some small points. The tool will throw an exception when trying to snoop a gradient hatch, so I fixed it and add a small feature that allows to snoop colors of gradient hatch.

**Comment by thanhsol** [comment]
For other files, just added references because there are errors in my visual studio.

**Comment by chuongmep** [comment]
Hi @thanhsol, I don't see any new feature in pull request you have required,
- [Hatch] Add gradient colors
- [Hatch] Fix bug when get definitions of gradient hatch
That is reason I will close this pull request, please create another pull request clearly if you want to do it. Thanks.

**Pull request closed without merging**
